source 'http://rubygems.org'

gem 'rails', '3.1.0'

gem 'devise', '~> 1.4.3'
gem 'dynamic_form'
gem 'jquery-rails'
gem 'sqlite3'

group :assets do
  gem 'coffee-rails', "~> 3.1.0"
  gem 'sass-rails', "  ~> 3.1.0"
  gem 'uglifier'
end

group :test, :development do
  gem 'rspec-rails', '~> 2.5'
end

group :test do
  gem 'capybara'
  gem 'cucumber-rails'
  gem 'factory_girl'
  gem 'database_cleaner'
  gem 'turn', :require => false
end
